//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [Display(Name = "Mã sản phẩm")]
        public int MaSP { get; set; }

        [Display(Name = "Tên sản phẩm")]
        public string TenSP { get; set; }

        [Display(Name = "Đơn giá")]
        public Nullable<decimal> DonGia { get; set; }

        [Display(Name = "Ngày cập nhật")]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }

        [Display(Name = "Cấu hình")]
        public string CauHinh { get; set; }

        [Display(Name = "Mô tả")]
        public string MoTa { get; set; }

        [Display(Name = "Hình ảnh")]
        public string HinhAnh { get; set; }

        [Display(Name = "Số lượng tồn")]
        public Nullable<int> SoLuongTon { get; set; }

        [Display(Name = "Lượt xem")]
        public Nullable<int> LuotXem { get; set; }

        [Display(Name = "Lượt bình chọn")]
        public Nullable<int> LuotBinhChon { get; set; }

        [Display(Name = "Lượt bình luận")]
        public Nullable<int> LuotBinhLuan { get; set; }

        [Display(Name = "Số lần mua")]
        public Nullable<int> SoLanMua { get; set; }

        [Display(Name = "Mới")]
        public Nullable<int> Moi { get; set; }

        [Display(Name = "Mã nhà CC")]
        public Nullable<int> MaNCC { get; set; }

        [Display(Name = "Mã nhà SX")]
        public Nullable<int> MaNSX { get; set; }

        [Display(Name = "Mã loại SP")]
        public Nullable<int> MaLoaiSP { get; set; }

        [Display(Name = "Đã Xóa")]
        public Nullable<int> DaXoa { get; set; }

        [Display(Name = "Hình ảnh 1")]
        public string HinhAnh1 { get; set; }

        [Display(Name = "Hình ảnh 2")]
        public string HinhAnh2 { get; set; }

        [Display(Name = "Hình ảnh 3")]
        public string HinhAnh3 { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}
